# site settings
title: Cryptoeconomics.hub
subtitle: null
email: cryptoeconomics.hub@gmail.com
description: Cryptoeconomics is the foudation of the decentralised world. Based on cryptography, game theory, mechanism design and network science, the objective is to align the incentives of the participants to achieve a global desirable outcome.
baseurl: # the subpath of your site, e.g. /blog
url: "https://www.cryptoeconomicshub.org" # the base hostname & protocol for your site
author:
venue: Cryptoeconomics Sunday
street_address: Sign up in Telegram
city:
state:
zip_code:
country:
phone:
telegram: https://t.me/cryptoeconomics

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:
telegram_url:
discord_url:
youtube_url:
medium_url:

# build settings
markdown: kramdown

sass:
  style: compressed
